### ISSUE TITLE
first ever reentrency attack

### ISSUE THREAD

**Issue by nmushegian** [pcaversaccio/reentrancy-attacks#1]
The first reentrency attck was a whitehack attack by me against my first WETH deployment. 

https://old.reddit.com/r/ethereum/comments/4nmohu/from_the_maker_dao_slack_today_we_discovered_a/

Here you can see me thank the researcher for pointing out this general class of issues, which made us realize our contract was vulnerable.

I can’t find it now because all the slockit websites have been deleted, but shortly after this post, TheDAO devs made a blog post boasting that their contract was not vulnerable. 

It has been a repeated theme for the last 5 years that people take worse versions of what I or some other good-faith inventor come up with, attach a scam token, and try to erase history. Please help preserve this historical record that TheDAO disaster could have been averted, but people who pay to market tokens to retail are more concerned about a quick flip than they are about building sound systems.

**Comment by pcaversaccio** [comment]
Thanks for informing me of this. A couple of backup links:
- https://webcache.googleusercontent.com/search?q=cache:RIUCLA8eN00J:https://blog.slock.it/the-history-of-the-dao-and-lessons-learned-d06740f8cfa5&hl=en&gl=ch&strip=1&vwsrc=0
- https://web.archive.org/web/20170615055530/http://vessenes.com/more-ethereum-attacks-race-to-empty-is-the-real-deal/
- https://www.reddit.com/r/ethereum/comments/4nmohu/from_the_maker_dao_slack_today_we_discovered_a/?user_id=360657100019&web_redirect=true

In the Reddit post a full post-mortem is mentioned. Can you please share that with me here as a link, thx.

**Comment by LefterisJP** [comment]
Hey @pcaversaccio there was indeed a post boasting the DAO is safe, but not by us devs. It was Stephan Tual who wanted to boast how cool the DAO is without asking us. You probably know how problematic his way of communication was. In fact I have had no time in between to look at stuff as I was away a bit in the few days between what Nikolai mentions and the actual DAO hack.

But I believe the class of attacks was indeed mentioned much earlier by Christian Reitwiessner. I don't remember where though. As for if there was a rentrancy attack in the wild by a malicious actor before I am not sure.

**Comment by pcaversaccio** [comment]
Thanks @LefterisJP for your comments. As you see above, I've compiled a list of archive URLs (e.g. the mentioned blog post from Stephan Tual is also part of this list) in order to preserve history. 

@chriseth is there some archive link where you pointed out to Peter Vessenes (probably on GitHub) there reentrancy attack vector. Would be cool to have it here as well.
![image](https://user-images.githubusercontent.com/25297591/180746100-0eb33394-96ea-435e-9c0b-9e9e81b2383d.png)

**Comment by chriseth** [comment]
There is also the talk I have at devcon 1 in London where I mentioned that when using `.send()` you have to prepare for callbacks: https://chriseth.github.io/notes/talks/safe_solidity/#/7

Peter might have been talking about this one: https://github.com/ethereum/solidity/pull/617/files# - it does not say more than what I already said in the talk.
But IIRC, we were acutally discussing the issue in more detail on gitter. I'm pretty sure this is archived somewhere.

**Comment by pcaversaccio** [comment]
awesome @chriseth! In order to preserve history, here is the Internet Archive link to Chris' talk:
- https://web.archive.org/web/20210506230130/https://chriseth.github.io/notes/talks/safe_solidity/#/7

@vessenes any chance you can point me to the Gitter logs?

**Comment by chriseth** [comment]
The room is https://gitter.im/ethereum/solidity or https://gitter.im/ethereum/solidity-dev - there should be tools that download the archives from the relevant days / weeks.

**Comment by pcaversaccio** [comment]
Found the following gist that simulates a reentrancy attack by @vessenes:
- https://gist.github.com/vessenes/9d84df668893c43dcd968ee28a03cd2b

Also, found the following Gitter conversation that discusses the reentrancy attack vector:
- https://gitter.im/ethereum/solidity?at=575a028d1cf76dd64535b913
![image](https://user-images.githubusercontent.com/25297591/180839728-bbed89ba-89d2-4a0c-8fdf-697185808071.png)

**Comment by Mylifechangefast** [comment]
Love this, thanks for the insights.

**Comment by Mylifechangefast** [comment]
> > Okay, can you tell me more about WETH9 please?
> 
> https://www.zellic.io/blog/formal-verification-weth/

Yeah, I'm on that.

But what I want to know is that the Supply of ETH has to be greater than WETH right?

I mean the whole concept about the invariant lookout in this https://www.zellic.io/blog/formal-verification-weth/, right?

**Comment by Mylifechangefast** [comment]
Which shouldn't be an issue.
