### ISSUE TITLE
Add XSURGE To The List

### ISSUE THREAD

**Issue by 0xNazgul** [pcaversaccio/reentrancy-attacks#3]
Consider adding XSURGE to the list it was an Flashloan + Reentrancy attack that lost $5 million. 

Date: August 16, 2021
[Medium Article](https://medium.com/@Knownsec_Blockchain_Lab/knownsec-blockchain-lab-comprehensive-analysis-of-xsurge-attacks-c83d238fbc55)
[bscscan link](https://bscscan.com/tx/0x8c93d6e5d6b3ec7478b4195123a696dbc82a3441be090e048fe4b33a242ef09d)

**Comment by pcaversaccio** [comment]
@0xNazgul thx for highlighting this attack - I added it to the list: https://github.com/pcaversaccio/reentrancy-attacks/commit/5c793003013fad6cb0b97789415b9daa6139259d.
